<?php


$tag = '';

if(array_key_exists('kayako_tag', $_POST)) {
	if($kayako->saveSettings($_POST)) {
		?><div class="updated"><p><strong><?php _e('Options saved Successfully!' ); ?></strong></p></div><?php
	}
	else {
		?><div class="updated"><p><strong><?php _e('Could not save' ); ?></strong></p></div><?php
	}
}

$settings = $kayako->getSettings();



if($settings && array_key_exists('kayako_tag', $settings)) {
	$tag = $settings['kayako_tag'];
}
?>

<div class="wrap">
	<?php    echo "<h2>" . __( 'Kayako fusion live chat setup', 'setup' ) . "</h2>"; ?>

	<form name="oscimp_form" method="post" action="<?php echo str_replace( '%7E', '~', $_SERVER['REQUEST_URI']); ?>">
		<?php    echo "<h4>" . __( 'Paste the tag generated by Kayako fusion here : ', 'oscimp_trdom' ) . "</h4>"; ?>
		<p style="vertical-align: top"><?php _e('Paste Here'); ?><textarea rows="10" cols="100" name="kayako_tag" id="kayako_tag"><?php echo $tag ?></textarea>

		<p class="submit">
		<input type="submit" name="Submit" value="<?php _e('Save', 'save' ) ?>" />
		</p>
	</form>
</div>